### ISSUE TITLE
Instagram login issue

### ISSUE THREAD

**Issue by Venuri-De-Silva** [yudhiesh/MalaysianPayGap#4]
I have been trying to log in after the "_**_instaloader --login=USERNAME profile venuuuuuu_0000--dirname-pattern={profile} --comments --no-profile-pic --post-metadata-txt="Caption: {caption}\n{likes} likes\n{comments} comments\n" --filename-pattern={date_utc:%Y}/{shortcode}_**_" but after entering the correct password it gives an error "**Login error: Wrong password.**"

**Comment by yudhiesh** [comment]
Is your username `venuuuuuu_0000`?

**Comment by yudhiesh** [comment]
If it is then try `instaloader --login=venuuuuuu_0000 profile malaysianpaygap --dirname-pattern={profile} --comments --no-profile-pic --post-metadata-txt="Caption: {caption}\n{likes} likes\n{comments} comments\n" --filename-pattern={date_utc:%Y}/{shortcode}`

**Comment by Venuri-De-Silva** [comment]
Yes, that is and thanks will check
