### ISSUE TITLE
What is `posts.csv`? How do i create one?

### ISSUE THREAD

**Issue by Nkzlxs** [yudhiesh/MalaysianPayGap#5]
I am following the 3 step process according to the README.md

during the last step, 
`bash scripts/entrypoints.sh`
where
`python ./src/main.py main-preprocess-comments`

i get this error
```
File "/bot_dir/src/preprocess_comments.py", line 88, in main_preprocess_comments
    df = pd.read_csv(data_path.as_posix())
    
FileNotFoundError: [Errno 2] No such file or directory: '/bot_dir/data/posts.csv'
```

Seems like it assume the existence of `./data/posts.csv` by default.

Please advice. thx

**Comment by yudhiesh** [comment]
@Nkzlxs `posts.csv` is created right [here](https://github.com/yudhiesh/MalaysianPayGap/blob/c250b0a8610310573f628a1100c3c0c82498f8de/src/preprocess_images.py#L142). The pipeline needs to be run in the correct order which is set [here](https://github.com/yudhiesh/MalaysianPayGap/blob/master/scripts/entrypoint.sh#L4) in the `entrypoint.sh`. But I think I made a mistake, in the order of the execution script. 

Could you try running it with this updated bash script?
```lang-bash
#!/bin/sh

python ./src/main.py main-preprocess-images &&  \
python ./src/main.py main-preprocess-comments && \
python ./src/main.py main-extract-text-images
```

**Comment by Nkzlxs** [comment]
@yudhiesh Yes, the updated bash script works.

But there are 2 more issue i found during the process of making it works


1. Seems like there's a typo

   i need to patch [this](https://github.com/yudhiesh/MalaysianPayGap/blob/c250b0a8610310573f628a1100c3c0c82498f8de/src/preprocess_comments.py#L108)
   ```python
   df_final = pd.concat(
         [df, df_comments, df_owner],
         axis=1,
   ).drop(["comments", "owner",0], axis=1)
   ```
      
   to this
   ```python
   df_final = pd.concat(
         [df, df_comments, df_owner],
         axis=1,
   ).drop(["comments", "owner"], axis=1)
   ```
    
2. `instaloader` will sometimes fetch `.webp` instead of `.jpg`, causing program to broke

   during a run test targeting others instagram account, `instaloader` fetched `.webp` instead of `.jpg` which [this](https://github.com/yudhiesh/MalaysianPayGap/blob/c250b0a8610310573f628a1100c3c0c82498f8de/src/preprocess_images.py#L122) line of code broke the program.

**Comment by yudhiesh** [comment]
> 

I see thanks for taking the time to figure out the problem. Could you make a PR with the changes made? I will test them out locally then accept the fixes.
